In [2]:
from netCDF4 import Dataset

hdf_file = r"G:\data\GLASS LAI\005Degree\rawData(2022-2024)\2022\GLASS01B01.V60.A2022001.2024107.hdf"
ds = Dataset(hdf_file)


In [3]:
print(ds)

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF4):
    HDFEOSVersion: HDFEOS_V2.20
    StructMetadata.0: GROUP=SwathStructure
END_GROUP=SwathStructure
GROUP=GridStructure
	GROUP=GRID_1
		GridName="GLASS01B01"
		XDim=7200
		YDim=3600
		UpperLeftPointMtrs=(-180000000.000000,90000000.000000)
		LowerRightMtrs=(180000000.000000,-90000000.000000)
		Projection=GCTP_GEO
		SphereCode=12
		PixelRegistration=HDFE_CENTER
		GROUP=Dimension
			OBJECT=Dimension_1
				DimensionName="YDim"
				Size=3600
			END_OBJECT=Dimension_1
			OBJECT=Dimension_2
				DimensionName="XDim"
				Size=7200
			END_OBJECT=Dimension_2
		END_GROUP=Dimension
		GROUP=DataField
			OBJECT=DataField_1
				DataFieldName="LAI"
				DataType=DFNT_UINT8
				DimList=("YDim","XDim")
			END_OBJECT=DataField_1
		END_GROUP=DataField
		GROUP=MergedFields
		END_GROUP=MergedFields
	END_GROUP=GRID_1
END_GROUP=GridStructure
GROUP=PointStructure
END_GROUP=PointStructure
END

    CoreMetadata.0: GROUP = INVENTORYMETADAT

In [4]:
var = ds.variables['LAI']
print("LAI 属性:")
for attr in var.ncattrs():
    print(attr, "=", getattr(var, attr))


LAI 属性:
_FillValue = 255
long_name = Leaf Area Index 8-Day 0.05-degrees GEO Grid
valid_range = [  0 100]
scale_factor = 0.1


In [5]:
from netCDF4 import Dataset

hdf_file = r"G:\data\MCD12C1 CMG\005Degree\MCD12C1.A2001001.061.2022146170409.hdf"
ds = Dataset(hdf_file)
print(ds)

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF4):
    HDFEOSVersion: HDFEOS_V2.19
    StructMetadata.0: GROUP=SwathStructure
END_GROUP=SwathStructure
GROUP=GridStructure
	GROUP=GRID_1
		GridName="MOD12C1"
		XDim=7200
		YDim=3600
		UpperLeftPointMtrs=(-180000000.000000,90000000.000000)
		LowerRightMtrs=(180000000.000000,-90000000.000000)
		Projection=GCTP_GEO
		GridOrigin=HDFE_GD_UL
		GROUP=Dimension
			OBJECT=Dimension_1
				DimensionName="Num_IGBP_Classes"
				Size=17
			END_OBJECT=Dimension_1
			OBJECT=Dimension_2
				DimensionName="Num_UMD_Classes"
				Size=14
			END_OBJECT=Dimension_2
			OBJECT=Dimension_3
				DimensionName="Num_LAI_FPAR_Classes"
				Size=11
			END_OBJECT=Dimension_3
		END_GROUP=Dimension
		GROUP=DataField
			OBJECT=DataField_1
				DataFieldName="Majority_Land_Cover_Type_1"
				DataType=DFNT_UINT8
				DimList=("YDim","XDim")
			END_OBJECT=DataField_1
			OBJECT=DataField_2
				DataFieldName="Majority_Land_Cover_Type_1_Assessment"
				DataT

In [15]:
from netCDF4 import Dataset
import numpy as np

hdf_file = r"G:\data\MCD12C1 CMG\005Degree\MCD12C1.A2001001.061.2022146170409.hdf"
ds = Dataset(hdf_file)

# 查看有哪些变量
print(ds.variables.keys())

# 获取 Land_Cover_Type_1_Percent 变量
var = ds.variables['Land_Cover_Type_1_Percent']  # shape: (17, 3600, 7200)

# 打印形状
print("shape:", var.shape)

# 打印第一维(类别0) 前5行×5列
print(var[100:105, 3600:3605, 0])


dict_keys(['Majority_Land_Cover_Type_1', 'Majority_Land_Cover_Type_1_Assessment', 'Land_Cover_Type_1_Percent', 'Majority_Land_Cover_Type_2', 'Majority_Land_Cover_Type_2_Assessment', 'Land_Cover_Type_2_Percent', 'Majority_Land_Cover_Type_3', 'Majority_Land_Cover_Type_3_Assessment', 'Land_Cover_Type_3_Percent'])
shape: (3600, 7200, 17)
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


dict_keys(['Majority_Land_Cover_Type_1', 'Majority_Land_Cover_Type_1_Assessment', 'Land_Cover_Type_1_Percent', 'Majority_Land_Cover_Type_2', 'Majority_Land_Cover_Type_2_Assessment', 'Land_Cover_Type_2_Percent', 'Majority_Land_Cover_Type_3', 'Majority_Land_Cover_Type_3_Assessment', 'Land_Cover_Type_3_Percent'])
shape: (3600, 7200)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
